spring.application.name=LAND-VALUATION-SERVICE

server.port=8081

# PostgreSQL datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/areap2
spring.datasource.username=postgres
spring.datasource.password=pgAdmin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000

SECRET_KEY =sagjsdghgasgfuyastksjajhasdfasfghfdfsjhdafkbfksdjbfdsbfbdsfsddfsfsd1234


spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.open-in-view=false