spring.application.name=LAND-VALUATION-SERVICE

server.port=8080

# PostgreSQL datasource configuration
spring.datasource.url=jdbc:postgresql://rdspg174r.c0d4088imfam.us-east-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Year2025
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000

SECRET_KEY =sagjsdghgasgfuyastksjajhasdfasfghfdfsjhdafkbfksdjbfdsbfbdsfsddfsfsd1234